[package]
name = "relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
async-stream = "0.3.2"
async-trait = "0.1.52"
dashmap = "5.0.0"
metrics = "0.18.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = { version = "1.0.75", features = ["raw_value"] }
thiserror = "1.0.30"
tokio = "1.15.0"
tokio-stream = "0.1.8"
tracing = "0.1.29"
